### ISSUE TITLE
KeyError with input file

### ISSUE THREAD

**Issue by pck00** [linxingchen/cobra#17]
Hello, 
I am running into this error: 

cobra-meta -f final.contigs.fa -q test.fa -c coverage.txt -m sorted_output.sam -a idba -mink 20 -maxk 140

/home/pck/anaconda3/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py:144: BiopythonDeprecationWarning: GC is deprecated; please use gc_fraction instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/pck/anaconda3/envs/cobra/bin/cobra-meta", line 10, in <module>
    sys.exit(main())
  File "/home/pck/anaconda3/envs/cobra/lib/python3.8/site-packages/cobra.py", line 878, in main
    if header2len[line.reference_name] > 1000:
KeyError: 'k141_2210 flag=1 multi=2.0000 len=345'

k141 is the very first contig in my input file, the only output file besides the log is COBRA_end_joining_pairs.txt

log: 
1. INPUT INFORMATION
# Assembler: IDBA_UD
# Min-kmer: 20
# Max-kmer: 140
# Overlap length: 139 bp
# Read mapping max mismatches for contig linkage: 2
# Query contigs: /home/pck/metagenome_seq/megahit_output/test.fa
# Whole contig set: /home/pck/metagenome_seq/megahit_output/final.contigs.fa
# Mapping file: /home/pck/metagenome_seq/megahit_output/sorted_output.sam
# Coverage file: /home/pck/metagenome_seq/megahit_output/coverage.txt
# Output folder: /home/pck/metagenome_seq/megahit_output/test.fa_COBRA

2. PROCESSING STEPS
[01/23] [2024/02/09 13:12:51] Reading contigs and getting the contig end sequences. A total of 3468 contigs were imported.
[02/23] [2024/02/09 13:12:51] Getting shared contig ends.
[03/23] [2024/02/09 13:12:51] Writing contig end joining pairs.
[04/23] [2024/02/09 13:12:51] Getting contig coverage information.
[05/23] [2024/02/09 13:12:51] Getting query contig list. A total of 1 query contigs were imported.
[06/23] [2024/02/09 13:12:51] Getting contig linkage based on sam/bam. Be patient, this may take long.

**Comment by linxingchen** [comment]
Hi,

1. It looks like your assembly was done by MEGAHIT not idba, you should change this in the commands `cobra-meta -f final.contigs.fa -q test.fa -c coverage.txt -m sorted_output.sam -a idba -mink 20 -maxk 140`, `-a megahit -mink 21 -maxk 141`
2. `/home/pck/anaconda3/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/init.py:144: BiopythonDeprecationWarning: GC is deprecated; please use gc_fraction instead.` this is likely due to the update of Biopython, the new one remove the function of GC that COBRA needs, please install an old version of Biopython if possible, version 1.81 works.
3. for `KeyError: 'k141_2210 flag=1 multi=2.0000 len=345'`, let's see if this still exists once you fix 1 and 2.

Thank you.

**Comment by pck00** [comment]
1) Silly me, forgot to change that. However, I am still getting the same error with
cobra-meta -f final.contigs.fa -q test.fa -c coverage.txt -m sorted_output.sam -a megahit -mink 20 -maxk 141.

2) I am running biopython 1.81 (any newer version gives the GC error even when running just cobra-meta). By the way it might just be that the newer biopython has changed GC to gc?

**Comment by linxingchen** [comment]
could you show me the exact errors you have for now after changing the commands?

importantly how did you get the bam/sam file? which software? It is likely that the contig names in the bam/sam file is too long.

**Comment by pck00** [comment]
Exact same error:
cobra-meta -f final.contigs.fa -q test.fa -c coverage.txt -m sorted_output.sam -a megahit -mink 21 -maxk 141
/home/pck/anaconda3/envs/cobra/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py:144: BiopythonDeprecationWarning: GC is deprecated; please use gc_fraction instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/pck/anaconda3/envs/cobra/bin/cobra-meta", line 10, in <module>
    sys.exit(main())
  File "/home/pck/anaconda3/envs/cobra/lib/python3.8/site-packages/cobra.py", line 878, in main
    if header2len[line.reference_name] > 1000:
KeyError: 'k141_2210 flag=1 multi=2.0000 len=345'

bam/sam files are from bbmap/samtools. Rerunning all that, I noticed this error for jgi_summarize: WARNING: your aligner reports an incorrect NM field.  You should run samtools calmd! nm < ins + del: cmatch=0 nm=0 ( insert=0 + del=59 + mismatch=0 == 59) SRR9161518.2361639 2361639 length=151. So it looks like an upstream issue...

**Comment by linxingchen** [comment]
Hi again,

For me it is likely that the new version of Biopython is still in function, not any older version. Could you please check that?

The error of `KeyError: 'k141_2210 flag=1 multi=2.0000 len=345'` is due to that the contig headers in your fasta file are different from those in your bam/sam file. COBRA will only take `k141_2210` as the name in this case, but the name in the bam/sam file is `'k141_2210 flag=1 multi=2.0000 len=345'`

**Comment by pck00** [comment]
A-ha, it was of course the contig names! Deleting everything after the space makes it run fine. Blame megahit, nobody can deal with those contig names.

I am still getting this error for jgi_summarize  WARNING: your aligner reports an incorrect NM field.  You should run samtools calmd! nm < ins + del: cmatch=0 nm=0 ( insert=0 + del=59 + mismatch=0 == 59) SRR9161518.2361639 2361639 length=151
but that doesn't seem to influence anything.

thanks!
